### ISSUE TITLE
Error on Write ADF when the scene was loaded from a YAML file and Meshes were not saved

### ISSUE THREAD

**Issue by FaridTavakol** [WPI-AIM/ambf_addon#14]
Hi Adnan,
When loading an ADF file in the blender using the extension, for instance, KUKA arm, and making some changes to the description file, for instance, controller gains, upon saving the new ADF file (or even overwriting the current one), the addon throws an error which says the mesh files should also be saved. I was wondering if there is a way to remove this dependency and link the already existing mesh files to the ADF file?

**Comment by adnanmunawar** [comment]
Hi Farid,
Thanks for bringing this to attention. I think the error is misleading as you probably don't have to actually save the meshes, just set the path to the meshes in the main AMBF addon panel. Can you try to do just that and don't click save meshes and see if the error still shows up.

**Comment by FaridTavakol** [comment]
> Hi Farid,
> Thanks for bringing this to attention. I think the error is misleading as you probably don't have to actually save the meshes, just set the path to the meshes in the main AMBF addon panel. Can you try to do just that and don't click save meshes and see if the error still shows up.

Thank you for your prompt response Adnan! Yes, that worked. I set the path to the mesh directory but didn't click on `save mesh` and just saved the new ADF file. It saved the files without any error message! :)
