### ISSUE TITLE
Fixed joint offsets appear to not scale correctly

### ISSUE THREAD

**Issue by htp2** [WPI-AIM/ambf_addon#16]
Other joints like rotary joints do. @adnanmunawar we discussed this today, here is the screenshot of the behavior.

![image](https://user-images.githubusercontent.com/17507145/221303191-e733ac82-e6bf-47f7-92e1-b8dc85f89758.png)

Here is the yaml and mesh files
[temp.zip](https://github.com/WPI-AIM/ambf_addon/files/10829135/temp.zip)

Here is the blender file
[ur5_w_act.zip](https://github.com/WPI-AIM/ambf_addon/files/10829142/ur5_w_act.zip)

Thanks!

**Comment by adnanmunawar** [comment]
Hi Henry, thanks for creating the issue. This is an issue with AMBF and thus I created a [related issue](https://github.com/WPI-AIM/ambf/issues/196) and fix. If you can test it, we can close the issue.

**Comment by htp2** [comment]
![image](https://user-images.githubusercontent.com/17507145/221591371-b1e80f79-420d-4764-aee3-2de3424e5273.png)

Worked like a charm! Thanks :+1:
