### ISSUE TITLE
OBJ file colors overwritten

### ISSUE THREAD

**Issue by htp2** [WPI-AIM/ambf_addon#17]
ADF file has color parameter that causes meshes saved with color as obj to have that color overriden. 

We could just not write that color parameter from the addon if a OBJ mesh is specified.

**Comment by adnanmunawar** [comment]
With the above commit, if saving the meshes as OBJ, a flag would be set for all the objects within the ADF file to ignore the custom set material. This will allow the material to be read from the OBJ files instead.

``` yaml
use material: False
```

**Comment by htp2** [comment]
Works like a charm! Thanks Adnan!
